name: "Validate"

on:
  push:
    branches: [ "main" ]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: .
          options: --quiet 
          show: all